version: '3.8'
services:
  app:
    build: .
    container_name: portfolio-app
    restart: unless-stopped
    networks:
      - web-network

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "1880:80"      # HTTP
      - "1443:443"    # HTTPS (optional)
    volumes:
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
