services:
  app:
    build: .
    container_name: portfolio-app
    restart: unless-stopped
    networks:
      - portfolio-network

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    depends_on:
      - app
    ports:
      - "1880:80"   # Local HTTP access
      - "1443:443"  # For future SSL
    volumes:
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

